// GENERATED by scripts/sync-function.mjs from src/server/types.ts. Edit the source, not this copy.
/**
 * Server-level (lobby + persistence) contract, shared by the Supabase Edge
 * Function and the in-browser local server. Deno-compatible: `.ts` imports only.
 */
import type { Action, ColorId, GameConfig, GameState, PlayerId, PlayerView } from '../engine/types.ts';

export type GameStatus = 'lobby' | 'playing' | 'finished';

export interface LobbyPlayer {
  id: PlayerId;
  name: string;
  color: ColorId;
  /** Clockwise order once the game starts (join order in the lobby). */
  seat: number;
  isBot: boolean;
}

/** Everything persisted for one game. SECRET: contains the full GameState. */
export interface GameRecord {
  code: string;
  hostId: PlayerId;
  status: GameStatus;
  config: GameConfig;
  players: LobbyPlayer[];
  state: GameState | null;
  /** Monotonic; bumped on every mutation (lobby or game). Broadcast to clients. */
  version: number;
  createdAt: string;
  updatedAt: string;
}

/** What one client receives. Safe to send to `youId`. */
export interface Snapshot {
  code: string;
  status: GameStatus;
  hostId: PlayerId;
  version: number;
  config: GameConfig;
  players: LobbyPlayer[];
  youId: PlayerId;
  /** null while in the lobby. */
  view: PlayerView | null;
}

/** Request body for the `game` edge function (POST JSON). */
export type ServerRequest =
  | { op: 'create'; name: string; color?: ColorId }
  | { op: 'join'; code: string; name: string; color?: ColorId }
  | { op: 'get'; code: string; token: string }
  | { op: 'updateLobby'; code: string; token: string; patch: LobbyPatch }
  | { op: 'addBot'; code: string; token: string }
  | { op: 'removePlayer'; code: string; token: string; playerId: PlayerId }
  | { op: 'start'; code: string; token: string }
  | { op: 'act'; code: string; token: string; action: Action }
  | { op: 'setBot'; code: string; token: string; playerId: PlayerId; isBot: boolean }
  | { op: 'rematch'; code: string; token: string }
  | { op: 'leave'; code: string; token: string };

export interface LobbyPatch {
  name?: string;
  color?: ColorId;
  /** Host only. */
  config?: Partial<GameConfig>;
}

export type ServerResponse<T> =
  | { ok: true; data: T }
  | { ok: false; error: { code: ServerErrorCode; message: string } };

export type ServerErrorCode =
  | 'bad_request'
  | 'not_found'
  | 'unauthorized'
  | 'forbidden'
  | 'full'
  | 'color_taken'
  | 'wrong_status'
  | 'illegal_action'
  | 'conflict'
  | 'internal';

/** Result of create/join: the token is the player's secret credential for this game. */
export interface JoinResult {
  playerId: PlayerId;
  token: string;
  snapshot: Snapshot;
}

/** Realtime channel for a game: public broadcast, event 'update', payload { version, status }. Presence key = playerId. */
export const channelName = (code: string) => `akabare:${code.toUpperCase()}`;
export const BROADCAST_EVENT = 'update';

export const CODE_ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
export const CODE_LENGTH = 5;
export const MAX_NAME_LENGTH = 20;
