#!/usr/bin/env node
/**
 * Final card-back export. src/cards/backs.ts is the only generator the app and print use.
 *
 *   node scripts/export-backs.mjs              # print masters + contact sheet + app webps
 *   node scripts/export-backs.mjs --check      # run scripts/check-backs.mjs first (fails on error)
 *   node scripts/export-backs.mjs --app-only   # skip the print masters: render the SVGs in-process
 *
 * Writes
 *   print/backs/{puri,power}-<color>.svg|.png  750×1050 print masters (librsvg), contact.png, strip-44.png
 *   public/backs/{puri,power}-<color>.webp     375×525   the app's 1x image (<Card> uses srcset/sizes, so
 *                                                       a 120 px card on a 3x phone still picks this one)
 *   public/backs/{puri,power}-<color>-2x.webp  750×1050  hi-dpi / large cards (the print master as webp)
 *   public/backs/version.txt                   BACK_VERSION + content rev the webps were made from
 *   src/cards/backImages.ts                    generated: BACK_IMAGE_REV (cache-busting query) and sizes
 *
 * Why bitmaps: the app draws dozens of backs (stacks, fans, hands); an inline SVG back re-runs its
 * turbulence/displacement filters for every copy, a bitmap costs nothing per copy.
 *
 * Quality tuning (compared crops at 3× zoom, see docs/CARD_BACKS.md):
 *   1x  lanczos3 750→375 (2× supersampled), then an edge-only unsharp mask (m1 0.2 flat / m2 2.5
 *       jagged) so the hairlines, stitches and wordmarks stay crisp without amplifying paper grain,
 *       webp q76 with smartSubsample (keeps chroma on thin red/green lines on coloured fields).
 *   2x  the 750 px master as-is, webp q76 smartSubsample.
 */
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { COLORS } from '../src/engine/types.ts';
import { BACK_VERSION, backSvg } from '../src/cards/backs.ts';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const run = (script, ...a) => {
  const r = spawnSync(process.execPath, [path.join(ROOT, 'scripts', script), ...a], { cwd: ROOT, stdio: 'inherit' });
  if (r.status !== 0) process.exit(r.status ?? 1);
};

const W1 = 375;
const H1 = 525;
const W2 = 750;
const H2 = 1050;
const WEBP = { quality: 76, effort: 6, smartSubsample: true };
const EDGE_SHARPEN = { sigma: 0.6, m1: 0.2, m2: 2.5 };

const APP_ONLY = args.includes('--app-only');
if (args.includes('--check')) run('check-backs.mjs', 'src/cards/backs.ts');
if (!APP_ONLY) run('render-backs.mjs', 'src/cards/backs.ts', 'print/backs');

/** 750×1050 PNG master: the print render when we just made it, otherwise render in-process. */
async function master(kind, color) {
  if (!APP_ONLY) return readFile(path.join(ROOT, 'print/backs', `${kind}-${color}.png`));
  return sharp(Buffer.from(backSvg(kind, color)), { density: 72 }).resize(W2, H2, { fit: 'fill' }).png().toBuffer();
}

const PUB = path.join(ROOT, 'public/backs');
await mkdir(PUB, { recursive: true });
const hash = createHash('sha256');
let total1 = 0;
let total2 = 0;
for (const kind of ['puri', 'power']) {
  for (const c of COLORS) {
    const png = await master(kind, c);
    const one = await sharp(png)
      .resize(W1, H1, { kernel: 'lanczos3', fit: 'fill' })
      .sharpen(EDGE_SHARPEN)
      .webp(WEBP)
      .toBuffer();
    const two = await sharp(png).resize(W2, H2, { fit: 'fill' }).webp(WEBP).toBuffer();
    await writeFile(path.join(PUB, `${kind}-${c}.webp`), one);
    await writeFile(path.join(PUB, `${kind}-${c}-2x.webp`), two);
    hash.update(one).update(two);
    total1 += one.length;
    total2 += two.length;
    console.log(`  ${`${kind}-${c}`.padEnd(14)} 1x ${(one.length / 1024).toFixed(1).padStart(5)} KB   2x ${(two.length / 1024).toFixed(1).padStart(6)} KB`);
  }
}
const rev = hash.digest('hex').slice(0, 10);
await writeFile(path.join(PUB, 'version.txt'), `${BACK_VERSION}\n${rev}\n`);
await writeFile(
  path.join(ROOT, 'src/cards/backImages.ts'),
  `/**
 * AUTO-GENERATED by scripts/export-backs.mjs — do not edit by hand.
 *
 * Pre-rendered card backs in public/backs/ (made from src/cards/backs.ts ${BACK_VERSION}).
 * BACK_IMAGE_REV is a content hash of all 24 webps, used as a cache-busting query
 * (?v=…) by backImageUrl() in Card.tsx. Kept in its own tiny module so the app bundle
 * never pulls in the SVG generator.
 */

export const BACK_IMAGE_VERSION = '${BACK_VERSION}';
export const BACK_IMAGE_REV = '${rev}';
/** Pixel sizes of the two variants: \`<kind>-<color>.webp\` and \`<kind>-<color>-2x.webp\`. */
export const BACK_IMAGE_SIZES = { x1: [${W1}, ${H1}], x2: [${W2}, ${H2}] } as const;
`,
);
console.log(
  `→ public/backs: 12 × ${W1}×${H1} (${(total1 / 1024).toFixed(0)} KB) + 12 × ${W2}×${H2} (${(total2 / 1024).toFixed(0)} KB), version ${BACK_VERSION}, rev ${rev}`,
);
console.log('→ src/cards/backImages.ts');
