/**
 * AUTO-GENERATED by scripts/export-backs.mjs — do not edit by hand.
 *
 * Pre-rendered card backs in public/backs/ (made from src/cards/backs.ts 1.0.0).
 * BACK_IMAGE_REV is a content hash of all 24 webps, used as a cache-busting query
 * (?v=…) by backImageUrl() in Card.tsx. Kept in its own tiny module so the app bundle
 * never pulls in the SVG generator.
 */

export const BACK_IMAGE_VERSION = '1.0.0';
export const BACK_IMAGE_REV = '4ad2671655';
/** Pixel sizes of the two variants: `<kind>-<color>.webp` and `<kind>-<color>-2x.webp`. */
export const BACK_IMAGE_SIZES = { x1: [375, 525], x2: [750, 1050] } as const;
